services:

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "5002:5000"
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: task-redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
